services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dipu67

  # MinIO service for local development (deprecated in favor of Cloudflare R2)
  # This is kept for backward compatibility and local testing
  # In production, use Cloudflare R2 storage instead
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set local http://minio:9000 minioadmin minioadmin123;
        mc mb --ignore-existing local/profile-images;
        mc mb --ignore-existing local/cover-images;
        mc mb --ignore-existing local/post-media;
        mc mb --ignore-existing local/chat-media;
        mc mb --ignore-existing local/group-media;
        mc anonymous set download local/profile-images;
        mc anonymous set download local/cover-images;
        mc anonymous set download local/post-media;
        mc anonymous set download local/chat-media;
        mc anonymous set download local/group-media;
        echo 'MinIO buckets created and configured';
        tail -f /dev/null
      "

 
volumes:
  mongo_data:
    driver: local
  minio_data:
    driver: local