version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: chat-app-minio
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Optional: MinIO Client (mc) for bucket management
  minio-client:
    image: minio/mc
    container_name: chat-app-minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/profile-images myminio/cover-images myminio/post-media myminio/chat-media myminio/group-media --ignore-existing;
      /usr/bin/mc anonymous set public myminio/profile-images myminio/cover-images myminio/post-media myminio/chat-media myminio/group-media;
      exit 0;
      "

volumes:
  minio_data:
